### PR TITLE
Update api.dart

### PR DESCRIPTION
**Pull request by ghuyfel**
Updated API version from 2.5 to 3.0

### CODE REVIEW

**Comment by PackRuble** [comment]
Hello! How much change will this transition affect? Will all models/features remain functional?

I'd probably prefer to add a user-selectable api option as a parameter in `OWMApi`, so that the user could prefer to change this manually.

**Comment by ghuyfel** [comment]
Hi, model-wise I don't see any difference. 

I believe the big difference is the API key management on their side when accessing the onecall endpoint. 

Version 2.5 seems to be deprecated on that endpoint. Unfortunately, I couldn't find any clear communication about it.

Here is the error message:

`{"message":"OwmApiException(code: 401, message: {\"cod\":401, \"message\": \"Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info.\"})` 

Clean version:

Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more [here](https://openweathermap.org/price). If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see [here](https://openweathermap.org/faq#error401) for more info.

I will update my pull request as I have just realised that version 3.0 only applies to [One Call API](https://openweathermap.org/api/one-call-3) endpoints.

**Comment by PackRuble** [comment]
@ghuyfel, when was your api key received? I have a 2 year free key and it right now works on all methods.

There is a possibility that the new keys don't fit the old api 2.5. 

Anyway, thanks for the encouragement. I want to refine this a bit and take the changes into the next version of the package. There is a great desire to give users the choice of which api they will use based on what "year of production" it is their key :)

**Comment by PackRuble** [comment]
Still, there are differences in the fields:
1. API 2.5
image

2. API 3
image


The `daily.summary` field appeared. And the field descriptions are different, this is important for documentation.

And that was just a quick glance, I didn't really look. I think it's worth working on more thoroughly and playing the "find 10 differences" game.

**Comment by PackRuble** [comment]
This was implemented in v1.1.0

Details in [changelog](https://github.com/PackRuble/weather_pack/blob/master/CHANGELOG.md#110---25-03-2024)

Also, in #9 some work is underway regarding the further implementation of One Call 3.0

@ghuyfel, Thank you for your interest in the project!

**Pull request closed without merging**
